let artista=[
    {foto: "https://firebasestorage.googleapis.com/v0/b/fotosantojos.appspot.com/o/artista%2F50%20cent.jpg?alt=media&token=24033592-aaaa-43ff-814c-25e441ba3a02",
    historia:'Jackson comenzó a rapear en el sótano de un amigo, el que usó para practicar. En 1996, un amigo lo presentó a Jam Master Jay de Run-DMC que estaba organizando su sello Jam Master Jay Records. Jay le enseñó cómo poder contar los compases, escribir los coros, estructurar las canciones, y hacer los registros. La primera aparición oficial de Jackson fue en una canción titulada "React" con el grupo Onyx en su álbum de 1998 Shut Em Down. Se acreditarán Jam Master Jay, como una influencia que le ayudó a mejorar su capacidad de escribir ganchos. Jay había producido el primer álbum de Jackson, sin embargo, nunca fue lanzado. En 1999, después de salir de Jam Master Jay, debido a las ventas de platino, productores de Trackmasters tomaron nota de Jackson, quien luego firmó para Columbia Records. Le enviaron a un estudio en el norte de Nueva York, donde se produjeron treinta y seis canciones en dos semanas. Dieciocho fueron incluidas en su álbum de lanzamiento no oficial, The Power of the Dollar de 2000 cuya publicación es continuamente aplazada'},

    {foto: "https://firebasestorage.googleapis.com/v0/b/fotosantojos.appspot.com/o/artista%2FDaddy.jpg?alt=media&token=3225ef12-2c60-4300-84e6-28ce6d947952",
    historia:'Daddy Yankee Sus primeras canciones las grabo con DJ Piro en los años 1989 y 1990 en las Lomas de Puerto Rico, Dicho por el en el DVD de Barrio fino en Directo. Inicia su carrera en la música en 1991 como invitado en los discos del productor DJ Playero, entre ellos, Playero 37 y Playero 38, los cuales salieron en ese mismo año, durante ese año, también sufrió un altercado debido a una balacera que se formó cerca del barrio donde vivía el artista; en donde no estaba relacionado, pero unas de las balas impactaron en su pierna, dejándolo herido y sangrando, para suerte, la bala no lo dejó en mal estado pero sí sin los sueños que tenía el mismo sobre ser un jugador profesional de béisbol, ya que la música para él era un pasatiempo; posteriormente seguiría definitivamente los rumbos musicales'},
    {foto: "https://firebasestorage.googleapis.com/v0/b/fotosantojos.appspot.com/o/artista%2Fdr.%20dre.jpg?alt=media&token=d76cfe15-17b3-445a-a1be-105c1ae52bd9",
    historia:'Andre Romelle Young (18 de febrero de 1965) es un rapero, productor, actor y empresario afroamericano. Su nombre artístico es Dr. Dre. Nació en Compton, California, Estados Unidos.  Sus padres, Theodore y Verna Young, lo tuvieron a temprana edad. Su padre era músico y tenía una banda llamada The Romells. Cuando tenía tres años tuvo que afrontar la separación de sus padres, él siguió viviendo con su madre que luego se casa con Curtis Crayon. La familia tuvo que padecer la violencia entre pandillas, ya que vivían en una zona marginal.'},

    {foto: "https://firebasestorage.googleapis.com/v0/b/fotosantojos.appspot.com/o/artista%2Feminem.jpg?alt=media&token=a76da498-a879-47ca-9b1c-ac211ba70d8f",
    historia:'Se le atribuye la popularización del hip hop en el centro de Estados Unidos y es aclamado por la crítica como uno de los mejores raperos de todos los tiempos.2​ Se considera que el éxito mundial y las obras aclamadas de Eminem rompieron las barreras raciales para la aceptación de los raperos blancos en la música popular. Si bien gran parte de su trabajo transgresor a fines de la década de 1990 y principios de la de 2000 lo hizo muy controvertido, llegó a ser una «representación» de la angustia popular de la clase baja estadounidense y ha sido citado como una influencia para muchos artistas de varios géneros.'},
    {foto: "https://firebasestorage.googleapis.com/v0/b/fotosantojos.appspot.com/o/artista%2Fice%20cube.jpg?alt=media&token=63db4e45-ee4c-452f-867b-15f4dab34da1",
    historia:'Los Ángeles, California, 15 de junio de 1969), conocido profesionalmente como Ice Cube, es un rapero y actor estadounidense. ​ Comenzó su carrera a finales de los años 80 como miembro del polémico grupo de gangsta rap, N.W.A., y posteriormente lanzó su exitosa carrera en solitario en la música y en el cine.'},

    {foto: "https://firebasestorage.googleapis.com/v0/b/fotosantojos.appspot.com/o/artista%2Fjay%20z.jpg?alt=media&token=7c7794c7-95ae-42be-a759-730a56e92ea3",
    historia:'Jay Z Nació el 4 de diciembre de 1969, originario de Marcy Houses, un proyecto de vivienda en el Bedford-Stuyvesant barrio de Brooklyn en Nueva York. El futuro "Jay Z", entonces conocido como Shawn Carter, fue abandonado por su padre y en 1982, le disparó a su hermano en el hombro por el robo de sus joyas. Carter asistió a la Escuela Eli Whitney, en Brooklyn, junto con el también futuro rapero AZ, hasta que fue cerrada. Después de haber asistido a la George Westinghouse y Carrera Escuela de Educación Secundaria Técnica en el Downtown de Brooklyn, con los futuros raperos y compañeros The Notorious B.I.G. y Busta Rhymes, y la Trenton Central High School en Trenton, Nueva Jersey, no se graduó. En su música hace comúnmente referencias a haber estado involucrado en la venta de crack.'},

    {foto: "https://firebasestorage.googleapis.com/v0/b/fotosantojos.appspot.com/o/artista%2Fsnnop%20dogg.jpg?alt=media&token=3d2a6c71-aaa6-4a9c-9999-29a096ff5383",historia:''},
    {foto: "",historia:''},
    {foto: "",historia:''},
    {foto: "",historia:''}
    


]